# Generated by Django 2.0.7 on 2018-07-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180712_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
